Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

In [6]:
import numpy as np

a) Addition of 2 in all the element

In [8]:
a = np.array([0,1,2,3,4])

In [9]:
print(a+2)

[2 3 4 5 6]


b) Multiply 3 with all the elements

In [11]:
print(a*3)

[ 0  3  6  9 12]


c) Divide every element by 2

In [12]:
print(a/2)

[0.  0.5 1.  1.5 2. ]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [13]:
arr = np.array([1,2,3,4,5])

In [15]:
print(np.flip(arr))

[5 4 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])

In [16]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
freq = np.bincount(x).argmax()
print("most frequent values:", freq)
print("Their indices:", np.where(x==freq)[0])

most frequent values: 1
Their indices: [0 5 7 8 9]


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [17]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
freq = np.bincount(y).argmax()
print("most frequent values:", freq)
print("Their indices:", np.where(y==freq)[0])

most frequent values: 1
Their indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

In [20]:
arr = np.array([[10,20,30], [40,50,60], [70,80,90]])

a) Access 1st row, 2nd column

In [26]:
print(arr[0][1])

20


b) Access 3rd row, 1st column

In [27]:
print(arr[2][0])

70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [24]:
om = np.linspace(10, 100, 25)

print("Array:", om)
print("Dimensions:", om.ndim)
print("Shape:", om.shape)
print("Total elements:", om.size)
print("Data type of elements:", om.dtype)
print("Total bytes consumed:", om.nbytes)

om_transposed = om.reshape(25, 1)
print("\nReshaped (Transposed) Array:\n", om_transposed)

print("\nUsing T attribute:\n", om.T)  


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type of elements: float64
Total bytes consumed: 200

Reshaped (Transposed) Array:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [25]:
ucs420_om = np.array([[10, 20, 30, 40], 
                             [50, 60, 70, 80], 
                             [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_om))
print("Median:", np.median(ucs420_om))
print("Max:", np.max(ucs420_om))
print("Min:", np.min(ucs420_om))
print("Unique elements:", np.unique(ucs420_om))

reshaped_ucs420_om = ucs420_om.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_om)

resized_ucs420_om = np.resize(ucs420_om, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_om)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
